# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Qr-Payment

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@master

    - uses: azure/docker-login@v1
      with:
        login-server: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_77123c9b467545a6a47dc7eeed9064b5 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1f5c956657c143568be0033e7e00278a }}

    - run: |
        docker build . -t index.docker.io/${{ secrets.AzureAppService_ContainerUsername_77123c9b467545a6a47dc7eeed9064b5 }}/openjdk:${{ github.sha }}
        docker push index.docker.io/${{ secrets.AzureAppService_ContainerUsername_77123c9b467545a6a47dc7eeed9064b5 }}/openjdk:${{ github.sha }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Qr-Payment'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3b448c24c4374e44949fa3035b438ace }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_77123c9b467545a6a47dc7eeed9064b5 }}/openjdk:${{ github.sha }}'